output_dir: results

connectivity:
  domains: [whitespace, wikitext]   
  n_tokens: 4096                    
  n_samples: 2                      
parcellation:
  n_networks: 20
  n_samples: 10

subnetwork_extraction: {}